### PR TITLE
displaying headers

### PR DESCRIPTION
**Pull request by aayushsaxena15**
I know that this part of the bug is solved already....but since this is still open, I just wanted to start off by having something done....it shows headers.....

### CODE REVIEW

**Comment by gautam1168** [comment]
I am not sure why I received this message.

I think you might be trying to merge into the wrong place. Because like you I am also applying for GSoC and I don't have the write permissions to merge into  the tardis master repository. If I understand correctly you have somehow made a pull request with my forked repo. I am relatively new to git so if this is wrong then please ignore this message.

**Comment by aayushsaxena15** [comment]
Oh yes. I am sorry for that. But when I tried to fork the repo (tardis), it
redirected me to to your repo. Could you please help me?

Thank you.
Aayush Saxena

**Comment by aayushsaxena15** [comment]
Got it...Thanks anyways...

**Comment by gautam1168** [comment]
I am sorry, I am new to github myself. But try following the developer
workflow given  here step by step:

http://tardis.readthedocs.org/en/latest/workflow/git_workflow.html

 Or maybe ask on the mailing list.

**Pull request closed without merging**
